language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
install:
- npm install
script: npm run build
after_success:
- bash .travis/push.sh
env:
  global:
    secure: CSiw+gG6FPKfaUY0xPcJ0O/2FkespV5iPPMV27D4chyek/0nm8b8A1Hs++mwnBoA+cncYPZMxVAreQu7KmNMV0kDmAn/F3OKP0G7pLII69Z9okhmLsj6+RkisbU49aLyrRCAcFbisar1uZxrhpngv/LD1tUnxueR5j6Hil1YAlvgsIFjFCiSxb/DlgJ8IGaK3/qRu6oOtFJcuG+UliBlRhaMBvcY/Qsni3GZqM3MnvCNImG1LOY/6o7qRXhmnav21wirR/TtwCw7YxEGgC/LljnTvBOutQ6O2wwKGipuV99RfpwRRHNbDMqi+FwP4p5hPcCJ28qQAVlq2kZK+R3KymQij5zyzijZfs7SNOZQ9H78nxGHXTiK+KplqPG6ezAZgrBGEw52CoGRoKaizmO+3qa/U7KDahaeF3eaB6C6MnIcVaTkqwiZY9JRADsllDzNpBO54qqMdT+K5Jxyn/sTqs0zEm/WjCwr9oodBLGBd/oRgEzTbtQKkyZewWGlJnwwGXcqegXXaMWVIl+v0hQW4KKPXM3GW5DRA/1IJVWs3Jno8dxYsSOR6ZpAmpG5xNxMVF6vIGwRBcVoZWmWH/sRT4u62rVsTfpMvgCjsHvD6lZ53Q1yOMa6bCeMeJWFFs8k5rQ3MWcBcGC+EZGw2fqBu5Cn0uK5znyVUZa6XZKLSvw=
