language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
install:
- npm install
script: npm run build
after_success:
- bash .travis/push.sh
env:
  global:
    secure: NG7eJzGlrR4DH6VOsTplxTbdFyyQRdNFMdYWyJLqswkkRxV9FSQ2TAwttvSqG9Tl0pbtApmRtTwv4+QZYBWpp9cfQjefbRzUO4DxHpCFRdHPPobWxkbE5y9YcWOYy1LfSjGNh1tb3ZBHfxvAn+/cxyCNvDNmOWKW9bHMtmAOZNWJ368joMbRt8hBqxjIM5CzOiU0hkPf7AIQcqka61A2xxSjq0O7sgkedJAncwzthHTFR2zSeZ5HKBcGohbEuyPgNSh1QUyGGItU4Cosx0ui6HZxuzPZBYanj5/oUFiFC4G0P085Ry/F4taLc72YTKtK14FYW1XvOCjFUFEaHdNCmSXLU/RW19zHSWGLuty5wXt8SG6cD8jKqjh7sP/S9YoY3FnDbPsmVGd9yTWPFAK15OjGLdkwlXfw2hRlYvkvVQOMj+7CZ7b/yemzoXLLoLxBb3Uk3a8ttLlg+t3XxzdanhGZc/VOMyGHy81AjBBMh5hv+7RIXL8RzGuEsHcXOuth+VGr6iInAuVm+GiotXQw2iArVMGQnVKKtUVQ91AyMN0CQYwkuuajiPXVzumWGmcUJ2Zh+Kygaf3nVzCy9CX6OBMsxdbUthEdfNOEuemKbPwcvKZ3sjP7Z0IZqsgLcst6v1jCcLxZ3laftmmpVPkPpPdizb5kokePQjYqKyU+pgQ=